<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class SyncServiceBoundaries extends Command
{
    protected $signature = 'services:sync-boundaries';

    protected $description = 'Generate per-service module status files, migration folders, and MySQL init SQL.';

    public function handle(): int
    {
        $boundaries = config('service_boundaries');
        $services = $boundaries['services'] ?? [];
        $allModules = File::exists(base_path('modules_statuses.json'))
            ? array_keys(json_decode(File::get(base_path('modules_statuses.json')), true) ?: [])
            : [];

        File::ensureDirectoryExists($boundaries['module_status_directory']);

        foreach ($services as $service => $definition) {
            $statusMap = array_fill_keys($allModules, false);

            foreach ($definition['modules'] ?? [] as $module) {
                $statusMap[$module] = true;
            }

            File::put(
                $definition['module_status_file'],
                json_encode($statusMap, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL
            );

            $this->line(sprintf('Module status synced: %s', $service));
        }

        $serviceMigrationRoot = base_path('database/migrations/services');
        File::ensureDirectoryExists($serviceMigrationRoot);

        foreach (array_keys($services) as $service) {
            if ($service === 'core') {
                continue;
            }

            File::ensureDirectoryExists($serviceMigrationRoot.'/'.$service);
        }

        foreach (($boundaries['migration_sources'] ?? []) as $service => $sources) {
            $targetDirectory = $serviceMigrationRoot.'/'.$service;
            File::ensureDirectoryExists($targetDirectory);

            foreach ($sources as $source) {
                if (! File::exists($source)) {
                    $this->warn(sprintf('Skipped missing migration source: %s', $source));
                    continue;
                }

                File::copy($source, $targetDirectory.'/'.basename($source));
            }

            $this->line(sprintf('Migration profile synced: %s', $service));
        }

        $sqlLines = [
            '-- Auto-generated by php artisan services:sync-boundaries',
            'CREATE USER IF NOT EXISTS \'erpgo_user\'@\'%\' IDENTIFIED BY \'erpgo_secret_2026\';',
            '',
        ];

        foreach (($boundaries['databases'] ?? []) as $definition) {
            $database = $definition['database'];

            $sqlLines[] = sprintf('CREATE DATABASE IF NOT EXISTS `%s` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;', $database);
            $sqlLines[] = sprintf('GRANT ALL PRIVILEGES ON `%s`.* TO \'erpgo_user\'@\'%%\';', $database);
        }

        $sqlLines[] = 'FLUSH PRIVILEGES;';
        $sqlLines[] = '';

        File::ensureDirectoryExists(dirname($boundaries['sql_init_path']));
        File::put($boundaries['sql_init_path'], implode(PHP_EOL, $sqlLines));

        $this->info('Service boundary artifacts synced.');

        return self::SUCCESS;
    }
}
