@extends('layouts.admin')
@section('page-title', __('Succession Plans'))
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a></li><li class="breadcrumb-item">{{ __('Succession Plans') }}</li>
@endsection
@section('action-btn')
    <div class="float-end d-flex">@can('create succession plan')<a href="#" data-url="{{ route('succession-plans.create') }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Create Succession Plan') }}" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a>@endcan</div>
@endsection
@section('content')
<div class="row"><div class="col-12"><div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable"><thead><tr><th>{{ __('Employee') }}</th><th>{{ __('Successor') }}</th><th>{{ __('Readiness') }}</th><th>{{ __('Status') }}</th><th width="220px">{{ __('Action') }}</th></tr></thead><tbody>@foreach($successionPlans as $successionPlan)<tr><td>{{ optional($successionPlan->employee)->name ?: '-' }}</td><td>{{ optional($successionPlan->successor)->name ?: '-' }}</td><td>{{ __(ucfirst($successionPlan->readiness_level)) }}</td><td>{{ __(ucfirst($successionPlan->status)) }}</td><td class="Action"><div class="action-btn me-2"><a href="{{ route('succession-plans.show',$successionPlan) }}" class="mx-3 btn btn-sm align-items-center bg-warning"><i class="ti ti-eye text-white"></i></a></div>@can('edit succession plan')<div class="action-btn me-2"><a href="#" data-url="{{ route('succession-plans.edit',$successionPlan) }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Edit Succession Plan') }}" class="mx-3 btn btn-sm align-items-center bg-info"><i class="ti ti-pencil text-white"></i></a></div>@endcan @can('delete succession plan')<div class="action-btn">{!! Form::open(['method'=>'DELETE','route'=>['succession-plans.destroy',$successionPlan],'id'=>'delete-form-succession-'.$successionPlan->id]) !!}<a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger" data-confirm="{{ __('Are You Sure?') . '|' . __('This action can not be undone. Do you want to continue?') }}" data-confirm-yes="document.getElementById('delete-form-succession-{{ $successionPlan->id }}').submit();"><i class="ti ti-trash text-white"></i></a>{!! Form::close() !!}</div>@endcan</td></tr>@endforeach</tbody></table></div></div></div></div></div>
@endsection
