@extends('layouts.admin')
@section('page-title'){{ __('CMDB') }}@endsection
@section('breadcrumb')<li class="breadcrumb-item"><a href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a></li><li class="breadcrumb-item">{{ __('CMDB') }}</li>@endsection
@section('action-btn')
<div class="float-end d-flex">@can('create configuration item')<a href="#" data-url="{{ route('configuration-items.create') }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Create Configuration Item') }}" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a>@endcan</div>
@endsection
@section('content')
<div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable"><thead><tr><th>{{ __('Item') }}</th><th>{{ __('Type') }}</th><th>{{ __('Owner') }}</th><th>{{ __('Asset') }}</th><th>{{ __('Criticality') }}</th><th>{{ __('Status') }}</th><th width="220px">{{ __('Action') }}</th></tr></thead><tbody>@foreach($items as $item)<tr><td><div>{{ $item->name }}</div><small class="text-muted">{{ $item->asset_tag ?: '-' }}</small></td><td>{{ $item->ci_type ?: '-' }}</td><td>{{ optional($item->owner)->name ?: '-' }}</td><td>{{ optional($item->asset)->name ?: '-' }}</td><td>{{ ucfirst($item->criticality ?: '-') }}</td><td>{{ ucfirst($item->status) }}</td><td class="Action"><div class="action-btn me-2"><a href="{{ route('configuration-items.show', $item->id) }}" class="mx-3 btn btn-sm align-items-center bg-warning"><i class="ti ti-eye text-white"></i></a></div>@can('edit configuration item')<div class="action-btn me-2"><a href="#" data-url="{{ route('configuration-items.edit', $item->id) }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Edit Configuration Item') }}" class="mx-3 btn btn-sm align-items-center bg-info"><i class="ti ti-pencil text-white"></i></a></div>@endcan @can('delete configuration item')<div class="action-btn">{!! Form::open(['method' => 'DELETE', 'route' => ['configuration-items.destroy', $item->id], 'id' => 'delete-form-ci-' . $item->id]) !!}<a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger" data-confirm="{{ __('Are You Sure?') . '|' . __('This action can not be undone. Do you want to continue?') }}" data-confirm-yes="document.getElementById('delete-form-ci-{{ $item->id }}').submit();"><i class="ti ti-trash text-white"></i></a>{!! Form::close() !!}</div>@endcan</td></tr>@endforeach</tbody></table></div></div></div>
@endsection
