<?php

namespace App\Services;

use App\Models\Integrations\Webhook;
use App\Models\Integrations\ZapierHook;
use App\Models\Task;
use App\Services\Core\AuditTrailService;
use App\Services\Core\NotificationCenter;
use App\Services\Core\WorkflowApprovalService;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Schema;

class WorkflowActionExecutor
{
    public function __construct(
        private readonly AuditTrailService $auditTrail,
        private readonly NotificationCenter $notificationCenter,
        private readonly WorkflowApprovalService $workflowApprovalService
    ) {
    }

    public function execute(array $action, $model, array $context = []): array
    {
        $type = $action['type'] ?? 'unknown';
        $data = $action['data'] ?? [];

        return match ($type) {
            'email' => $this->sendEmail($data, $model, $context),
            'notification' => $this->createNotification($data, $model, $context),
            'task' => $this->createTask($data, $model, $context),
            'update_field' => $this->updateField($data, $model, $context),
            'webhook' => $this->dispatchWebhook($data, $model, $context),
            'audit_log' => $this->writeAuditLog($data, $model, $context),
            'approval_request' => $this->createApprovalRequest($data, $model, $context),
            'zapier_hook' => $this->dispatchZapierHook($data, $model, $context),
            default => [
                'type' => $type,
                'status' => 'skipped',
                'message' => 'Unsupported workflow action.',
            ],
        };
    }

    private function sendEmail(array $data, $model, array $context): array
    {
        $to = $this->interpolate($data['to'] ?? null, $model, $context);
        $subject = $this->interpolate($data['subject'] ?? 'Workflow notification', $model, $context);
        $body = $this->interpolate($data['body'] ?? '', $model, $context);

        if (blank($to)) {
            return ['type' => 'email', 'status' => 'skipped', 'message' => 'Missing recipient.'];
        }

        Mail::raw($body, static function ($message) use ($to, $subject) {
            $message->to($to)->subject($subject);
        });

        return ['type' => 'email', 'status' => 'success', 'message' => 'Email dispatched.', 'recipient' => $to];
    }

    private function createNotification(array $data, $model, array $context): array
    {
        if (! Schema::hasTable('notifications')) {
            return ['type' => 'notification', 'status' => 'skipped', 'message' => 'Notifications table is not available.'];
        }

        $userId = (int) ($this->interpolate($data['user_id'] ?? ($context['owner_id'] ?? null), $model, $context));
        if ($userId <= 0) {
            return ['type' => 'notification', 'status' => 'skipped', 'message' => 'Missing target user.'];
        }

        $notification = $this->notificationCenter->create(
            $userId,
            'workflow_notification',
            [
                'message' => $this->interpolate($data['message'] ?? ($data['body'] ?? 'Workflow notification'), $model, $context),
                'model_type' => get_class($model),
                'model_id' => $model->id ?? null,
                'updated_by' => $context['triggered_by'] ?? null,
                'url' => $data['url'] ?? null,
                'icon' => $data['icon'] ?? 'ti ti-bolt',
                'icon_color' => $data['icon_color'] ?? 'notif-system',
            ],
            [
                'created_by' => $context['owner_id'] ?? ($model->created_by ?? 0),
            ]
        );

        if (! $notification) {
            return ['type' => 'notification', 'status' => 'skipped', 'message' => 'Notification disabled by preferences.'];
        }

        return ['type' => 'notification', 'status' => 'success', 'message' => 'Notification created.', 'user_id' => $userId];
    }

    private function createTask(array $data, $model, array $context): array
    {
        if (! Schema::hasTable('tasks')) {
            return ['type' => 'task', 'status' => 'skipped', 'message' => 'Tasks table is not available.'];
        }

        $task = Task::create([
            'title' => $this->interpolate($data['title'] ?? 'Workflow task', $model, $context),
            'date' => $this->interpolate($data['due_date'] ?? now()->toDateString(), $model, $context),
            'description' => $this->interpolate($data['body'] ?? ($data['message'] ?? 'Generated by workflow'), $model, $context),
            'module_type' => get_class($model),
            'module_id' => $model->id ?? null,
            'created_by' => $context['owner_id'] ?? ($model->created_by ?? 0),
        ]);

        return ['type' => 'task', 'status' => 'success', 'message' => 'Task created.', 'task_id' => $task->id];
    }

    private function updateField(array $data, $model, array $context): array
    {
        $field = $data['field'] ?? null;
        if (! $field) {
            return ['type' => 'update_field', 'status' => 'skipped', 'message' => 'Missing target field.'];
        }

        $model->{$field} = $this->interpolate($data['value'] ?? null, $model, $context);
        $model->save();

        return ['type' => 'update_field', 'status' => 'success', 'message' => 'Field updated.', 'field' => $field];
    }

    private function dispatchWebhook(array $data, $model, array $context): array
    {
        $payload = [
            'event' => $context['event'] ?? class_basename($model).'.updated',
            'model_type' => get_class($model),
            'model_id' => $model->id ?? null,
            'body' => $this->interpolate($data['body'] ?? null, $model, $context),
            'attributes' => method_exists($model, 'getAttributes') ? $model->getAttributes() : [],
        ];

        $url = $this->interpolate($data['url'] ?? null, $model, $context);
        if (filled($url)) {
            $method = strtoupper($data['method'] ?? 'POST');
            Http::timeout(15)->send($method, $url, ['json' => $payload]);

            return ['type' => 'webhook', 'status' => 'success', 'message' => 'Direct webhook dispatched.', 'url' => $url];
        }

        $ownerId = $context['owner_id'] ?? ($model->created_by ?? null);
        if (! $ownerId) {
            return ['type' => 'webhook', 'status' => 'skipped', 'message' => 'Missing owner for integration lookup.'];
        }

        $count = 0;
        foreach (Webhook::query()->where('user_id', $ownerId)->where('is_active', true)->get() as $hook) {
            if ($hook->trigger($payload['event'], $payload)) {
                $count++;
            }
        }

        return ['type' => 'webhook', 'status' => 'success', 'message' => 'Configured webhooks triggered.', 'count' => $count];
    }

    private function writeAuditLog(array $data, $model, array $context): array
    {
        $log = $this->auditTrail->record(
            $this->interpolate($data['action'] ?? ($context['event'] ?? 'workflow.executed'), $model, $context),
            [
                'user_id' => $context['triggered_by'] ?? 0,
                'route' => $context['route'] ?? null,
                'method' => $context['method'] ?? 'WORKFLOW',
                'ip_address' => $context['ip_address'] ?? null,
                'user_agent' => $context['user_agent'] ?? 'workflow-engine',
                'auditable' => $model,
                'old_values' => $data['old_values'] ?? null,
                'new_values' => [
                    'workflow' => $context['workflow_name'] ?? null,
                    'body' => $this->interpolate($data['body'] ?? null, $model, $context),
                ],
                'created_by' => $context['owner_id'] ?? ($model->created_by ?? 0),
                'created_at' => now(),
            ]
        );

        return ['type' => 'audit_log', 'status' => 'success', 'message' => 'Audit log stored.', 'audit_log_id' => $log?->id];
    }

    private function createApprovalRequest(array $data, $model, array $context): array
    {
        $request = $this->workflowApprovalService->createRequest($model, $data, $context);

        return [
            'type' => 'approval_request',
            'status' => 'success',
            'message' => 'Approval request created.',
            'approval_request_id' => $request->id,
        ];
    }

    private function dispatchZapierHook(array $data, $model, array $context): array
    {
        $ownerId = $context['owner_id'] ?? ($model->created_by ?? null);
        if (! $ownerId) {
            return ['type' => 'zapier_hook', 'status' => 'skipped', 'message' => 'Missing owner for Zapier hooks.'];
        }

        $event = $this->interpolate($data['event'] ?? ($context['event'] ?? class_basename($model).'.updated'), $model, $context);
        $payload = [
            'event' => $event,
            'model_type' => get_class($model),
            'model_id' => $model->id ?? null,
            'attributes' => method_exists($model, 'getAttributes') ? $model->getAttributes() : [],
        ];

        $count = 0;
        foreach (ZapierHook::query()->where('user_id', $ownerId)->where('event', $event)->where('is_active', true)->get() as $hook) {
            if ($hook->trigger($payload)) {
                $count++;
            }
        }

        return ['type' => 'zapier_hook', 'status' => 'success', 'message' => 'Zapier hooks triggered.', 'count' => $count];
    }

    private function interpolate($value, $model, array $context = [])
    {
        if (! is_string($value)) {
            return $value;
        }

        return preg_replace_callback('/\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}/', function (array $matches) use ($model, $context) {
            $token = $matches[1];

            if (str_starts_with($token, 'context.')) {
                return (string) data_get($context, substr($token, 8), '');
            }

            return (string) data_get($model, $token, '');
        }, $value);
    }
}
