@extends('layouts.admin')
@section('page-title', __('Plan Addons'))
@section('page-subtitle', __('Create addon offers, activate them for tenants and monitor subscription lifecycle.'))
@section('content')
<div class="row">
<div class="col-md-5"><div class="card"><div class="card-header"><h5>{{ __('Create Addon') }}</h5></div><div class="card-body"><form method="POST" action="{{ route('core.addons.store') }}">@csrf <div class="mb-2"><input type="text" name="name" class="form-control" placeholder="{{ __('Name') }}" required></div><div class="mb-2"><input type="text" name="code" class="form-control" placeholder="{{ __('Code') }}" required></div><div class="mb-2"><input type="number" step="0.01" name="price" class="form-control" placeholder="{{ __('Price') }}"></div><div class="mb-2"><input type="text" name="description" class="form-control" placeholder="{{ __('Description') }}"></div><div class="mb-2"><select name="billing_cycle" class="form-control"><option value="monthly">{{ __('Monthly') }}</option><option value="yearly">{{ __('Yearly') }}</option><option value="one_time">{{ __('One time') }}</option></select></div><button class="btn btn-primary">{{ __('Save Addon') }}</button></form></div></div></div>
<div class="col-md-7">
    <div class="card mb-3"><div class="card-header"><h5>{{ __('Addon Catalog') }}</h5></div><div class="card-body"><table class="table"><thead><tr><th>{{ __('Name') }}</th><th>{{ __('Price') }}</th><th>{{ __('Cycle') }}</th><th>{{ __('Action') }}</th></tr></thead><tbody>@foreach($addons as $addon)<tr><td>{{ $addon->name }}</td><td>{{ $addon->price }}</td><td>{{ ucfirst(str_replace('_', ' ', $addon->billing_cycle)) }}</td><td><div class="d-flex gap-2 flex-wrap"><form method="POST" action="{{ route('core.addons.activate', $addon) }}">@csrf <button class="btn btn-sm btn-success">{{ __('Activate for Tenant') }}</button></form><form method="POST" action="{{ route('core.addons.requests.store') }}">@csrf <input type="hidden" name="plan_addon_id" value="{{ $addon->id }}"><button class="btn btn-sm btn-outline-primary">{{ __('Request') }}</button></form></div></td></tr>@endforeach</tbody></table></div></div>
    <div class="card"><div class="card-header"><h5>{{ __('Tenant Addon Subscriptions') }}</h5></div><div class="card-body"><table class="table"><thead><tr><th>{{ __('Addon') }}</th><th>{{ __('Status') }}</th><th>{{ __('Amount') }}</th><th>{{ __('Renews') }}</th><th>{{ __('Action') }}</th></tr></thead><tbody>@forelse($subscriptions as $subscription)<tr><td><div>{{ optional($subscription->addon)->name ?: '-' }}</div><div class="small text-muted">{{ ucfirst(str_replace('_', ' ', $subscription->billing_cycle ?: optional($subscription->addon)->billing_cycle ?: '-')) }}</div></td><td>{{ ucfirst($subscription->status) }}</td><td>{{ $subscription->amount }}</td><td>{{ optional($subscription->renews_at)->format('Y-m-d') ?: '-' }}</td><td>@if($subscription->status === 'active')<div class="d-flex gap-2 flex-wrap"><form method="POST" action="{{ route('core.addons.renew', $subscription) }}">@csrf <button class="btn btn-sm btn-outline-primary">{{ __('Renew') }}</button></form><form method="POST" action="{{ route('core.addons.deactivate', $subscription) }}">@csrf <button class="btn btn-sm btn-outline-danger">{{ __('Deactivate') }}</button></form></div>@else <span class="text-muted">{{ __('Closed') }}</span>@endif</td></tr>@empty<tr><td colspan="5" class="text-muted">{{ __('No tenant addon subscriptions yet.') }}</td></tr>@endforelse</tbody></table></div></div>
    <div class="card mt-3"><div class="card-header"><h5>{{ __('Addon Requests') }}</h5></div><div class="card-body table-border-style"><table class="table"><thead><tr><th>{{ __('Addon') }}</th><th>{{ __('Tenant') }}</th><th>{{ __('Requested By') }}</th><th>{{ __('Status') }}</th><th>{{ __('Cycle') }}</th><th>{{ __('Review') }}</th><th>{{ __('Action') }}</th></tr></thead><tbody>@forelse($addonRequests as $request)<tr><td><div>{{ optional($request->addon)->name ?: '-' }}</div>@if($request->request_note)<div class="small text-muted">{{ $request->request_note }}</div>@endif</td><td>{{ $request->created_by }}</td><td>{{ optional($request->requester)->name ?: '-' }}</td><td>{{ ucfirst($request->status) }}</td><td>{{ ucfirst(str_replace('_', ' ', $request->billing_cycle ?: '-')) }}</td><td>@if($request->reviewer)<div>{{ optional($request->reviewer)->name }}</div><div class="small text-muted">{{ optional($request->reviewed_at)->format('Y-m-d H:i') ?: '-' }}</div>@if($request->review_note)<div class="small text-muted">{{ $request->review_note }}</div>@endif @else<span class="text-muted">{{ __('Pending review') }}</span>@endif</td><td>@if($request->status === 'pending' && \Auth::user()->type === 'super admin')<div class="d-flex gap-2"><form method="POST" action="{{ route('core.addons.requests.approve', $request) }}">@csrf <button class="btn btn-sm btn-success">{{ __('Approve') }}</button></form><form method="POST" action="{{ route('core.addons.requests.reject', $request) }}">@csrf <input type="hidden" name="review_note" value="{{ __('Rejected from addon cockpit') }}"><button class="btn btn-sm btn-outline-danger">{{ __('Reject') }}</button></form></div>@else<span class="text-muted">{{ ucfirst($request->status) }}</span>@endif</td></tr>@empty<tr><td colspan="7" class="text-muted">{{ __('No addon requests recorded yet.') }}</td></tr>@endforelse</tbody></table></div></div>
    @if($usageSummary->isNotEmpty())
        <div class="card mt-3"><div class="card-header"><h5>{{ __('Quota Pressure') }}</h5></div><div class="card-body">@foreach($usageSummary as $usage)<div class="mb-3"><div class="d-flex justify-content-between mb-1"><span>{{ $usage['metric_key'] }}</span><span class="small text-muted">{{ $usage['usage_value'] }} / {{ $usage['limit_value'] ?: __('Unlimited') }}</span></div>@if(!is_null($usage['ratio']))<div class="progress" style="height:8px;"><div class="progress-bar {{ $usage['ratio'] >= 90 ? 'bg-danger' : ($usage['ratio'] >= 70 ? 'bg-warning' : 'bg-success') }}" style="width: {{ $usage['ratio'] }}%"></div></div>@endif</div>@endforeach</div></div>
    @endif
</div>
</div>
@endsection
