@extends('layouts.admin')
@section('page-title', __('Saved Views'))
@section('page-subtitle', __('Store recurring filters, default list contexts and personal workspaces for repeated operations.'))
@section('content')
<div class="row">
<div class="col-md-5"><div class="card ux-list-card"><div class="card-header"><h5>{{ __('Create Saved View') }}</h5></div><div class="card-body"><form method="POST" action="{{ route('core.saved-views.store') }}">@csrf <div class="mb-3"><label class="form-label">{{ __('Module key') }}</label><input type="text" name="module" class="form-control" placeholder="{{ __('invoice, projects, leads...') }}" required></div><div class="mb-3"><label class="form-label">{{ __('View name') }}</label><input type="text" name="name" class="form-control" placeholder="{{ __('Month-end receivables') }}" required></div><div class="mb-3"><label class="form-label">{{ __('Primary filter') }}</label><input type="text" name="filters[search]" class="form-control" placeholder="{{ __('Overdue, urgent, active...') }}"></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_default" value="1"><label class="form-check-label">{{ __('Default view') }}</label></div><button class="btn btn-primary w-100">{{ __('Save View') }}</button></form></div></div></div>
<div class="col-md-7"><div class="card ux-list-card"><div class="card-header"><h5>{{ __('My Saved Views') }}</h5></div><div class="card-body"><table class="table"><thead><tr><th>{{ __('Module') }}</th><th>{{ __('Name') }}</th><th>{{ __('Filters') }}</th><th>{{ __('Default') }}</th><th></th></tr></thead><tbody>@forelse($views as $view)<tr><td><strong>{{ $view->module }}</strong></td><td>{{ $view->name }}</td><td><span class="text-muted small">{{ data_get($view->payload, 'filters.search', __('No quick filter')) }}</span></td><td>{{ $view->is_default ? __('Yes') : __('No') }}</td><td><form method="POST" action="{{ route('core.saved-views.destroy', $view) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-danger">{{ __('Delete') }}</button></form></td></tr>@empty<tr><td colspan="5" class="text-muted">{{ __('No saved views yet.') }}</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
