@extends('layouts.admin')
@section('page-title', __('LIMS Records'))
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a></li><li class="breadcrumb-item">{{ __('LIMS Records') }}</li>
@endsection
@section('action-btn')
    <div class="float-end d-flex">@can('create lims record')<a href="#" data-url="{{ route('lims-records.create') }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Create LIMS Record') }}" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a>@endcan</div>
@endsection
@section('content')
<div class="row"><div class="col-12"><div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable"><thead><tr><th>{{ __('Sample') }}</th><th>{{ __('Test') }}</th><th>{{ __('Product') }}</th><th>{{ __('Status') }}</th><th width="220px">{{ __('Action') }}</th></tr></thead><tbody>@foreach($limsRecords as $limsRecord)<tr><td><div>{{ $limsRecord->sample_code }}</div><small class="text-muted">{{ $limsRecord->lot_reference ?: '-' }}</small></td><td>{{ $limsRecord->test_type }}</td><td>{{ optional($limsRecord->productService)->name ?: '-' }}</td><td>{{ __(ucfirst(str_replace('_',' ',$limsRecord->status))) }}</td><td class="Action"><div class="action-btn me-2"><a href="{{ route('lims-records.show',$limsRecord) }}" class="mx-3 btn btn-sm align-items-center bg-warning"><i class="ti ti-eye text-white"></i></a></div>@can('edit lims record')<div class="action-btn me-2"><a href="#" data-url="{{ route('lims-records.edit',$limsRecord) }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Edit LIMS Record') }}" class="mx-3 btn btn-sm align-items-center bg-info"><i class="ti ti-pencil text-white"></i></a></div>@endcan @can('delete lims record')<div class="action-btn">{!! Form::open(['method'=>'DELETE','route'=>['lims-records.destroy',$limsRecord],'id'=>'delete-form-lims-'.$limsRecord->id]) !!}<a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger" data-confirm="{{ __('Are You Sure?') . '|' . __('This action can not be undone. Do you want to continue?') }}" data-confirm-yes="document.getElementById('delete-form-lims-{{ $limsRecord->id }}').submit();"><i class="ti ti-trash text-white"></i></a>{!! Form::close() !!}</div>@endcan</td></tr>@endforeach</tbody></table></div></div></div></div></div>
@endsection
