@extends('layouts.admin')
@section('page-title', __('API Clients'))
@section('page-subtitle', __('Issue dedicated credentials, inspect traffic and govern partner integrations.'))
@section('action-btn')<div class="d-flex gap-2"><a href="{{ route('api-clients.docs') }}" class="btn btn-sm btn-light">{{ __('Docs') }}</a><a href="{{ route('api-clients.create') }}" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a></div>@endsection
@section('content')
<div class="row mb-3">
    <div class="col-md-3"><div class="card"><div class="card-body"><h6>{{ __('Clients') }}</h6><h3>{{ $stats['clients'] }}</h3></div></div></div>
    <div class="col-md-3"><div class="card"><div class="card-body"><h6>{{ __('Recent API Calls') }}</h6><h3>{{ $recentLogs->count() }}</h3></div></div></div>
    <div class="col-md-3"><div class="card"><div class="card-body"><h6>{{ __('Active Keys') }}</h6><h3>{{ $stats['active'] }}</h3></div></div></div>
    <div class="col-md-3"><div class="card"><div class="card-body"><h6>{{ __('Failed Calls') }}</h6><h3>{{ $stats['failedCalls'] }}</h3></div></div></div>
</div>
<div class="card mb-3"><div class="card-body table-border-style"><table class="table"><thead><tr><th>{{ __('Name') }}</th><th>{{ __('Key') }}</th><th>{{ __('Status') }}</th><th>{{ __('Usage') }}</th><th>{{ __('Last Used') }}</th><th>{{ __('Expires') }}</th><th>{{ __('Action') }}</th></tr></thead><tbody>@foreach($clients as $client)<tr><td>{{ $client->name }}</td><td><code>{{ $client->client_key }}</code></td><td><span class="badge {{ $client->is_active ? 'bg-success' : 'bg-danger' }}">{{ $client->is_active ? __('Active') : __('Inactive') }}</span></td><td>{{ $client->logs_count }}</td><td>{{ optional($client->last_used_at)->diffForHumans() ?: '-' }}</td><td>{{ optional($client->expires_at)->format('Y-m-d') ?: '-' }}</td><td><div class="d-flex gap-2 flex-wrap"><a href="{{ route('api-clients.show', $client) }}" class="btn btn-sm btn-light">{{ __('Open') }}</a><form method="POST" action="{{ route('api-clients.toggle-status', $client) }}">@csrf <button class="btn btn-sm btn-secondary">{{ $client->is_active ? __('Disable') : __('Enable') }}</button></form><form method="POST" action="{{ route('api-clients.destroy', $client) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-danger">{{ __('Delete') }}</button></form></div></td></tr>@endforeach</tbody></table></div></div>
<div class="card"><div class="card-header"><h5 class="mb-0">{{ __('Recent API Logs') }}</h5></div><div class="card-body table-border-style"><table class="table"><thead><tr><th>{{ __('When') }}</th><th>{{ __('Client') }}</th><th>{{ __('Route') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@forelse($recentLogs as $log)<tr><td>{{ optional($log->requested_at)->format('Y-m-d H:i') }}</td><td>{{ optional($log->apiClient)->name ?: '-' }}</td><td><code>{{ $log->route }}</code></td><td>{{ $log->status_code ?: '-' }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">{{ __('No API logs captured yet.') }}</td></tr>@endforelse</tbody></table></div></div>
@endsection
