@extends('layouts.admin')
@section('page-title', __('Transport Shipments'))
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a></li><li class="breadcrumb-item">{{ __('Transport Shipments') }}</li>
@endsection
@section('action-btn')
    <div class="float-end d-flex">@can('create transport shipment')<a href="#" data-url="{{ route('transport-shipments.create') }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Create Transport Shipment') }}" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a>@endcan</div>
@endsection
@section('content')
<div class="row"><div class="col-12"><div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable"><thead><tr><th>{{ __('Reference') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Route') }}</th><th>{{ __('Status') }}</th><th width="220px">{{ __('Action') }}</th></tr></thead><tbody>@foreach($transportShipments as $transportShipment)<tr><td>{{ $transportShipment->reference }}</td><td>{{ optional($transportShipment->customer)->name ?: '-' }}</td><td>{{ $transportShipment->origin }} <i class="ti ti-arrow-right"></i> {{ $transportShipment->destination }}</td><td>{{ __(ucfirst(str_replace('_',' ',$transportShipment->status))) }}</td><td class="Action"><div class="action-btn me-2"><a href="{{ route('transport-shipments.show',$transportShipment) }}" class="mx-3 btn btn-sm align-items-center bg-warning"><i class="ti ti-eye text-white"></i></a></div>@can('edit transport shipment')<div class="action-btn me-2"><a href="#" data-url="{{ route('transport-shipments.edit',$transportShipment) }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Edit Transport Shipment') }}" class="mx-3 btn btn-sm align-items-center bg-info"><i class="ti ti-pencil text-white"></i></a></div>@endcan @can('delete transport shipment')<div class="action-btn">{!! Form::open(['method'=>'DELETE','route'=>['transport-shipments.destroy',$transportShipment],'id'=>'delete-form-shipment-'.$transportShipment->id]) !!}<a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger" data-confirm="{{ __('Are You Sure?') . '|' . __('This action can not be undone. Do you want to continue?') }}" data-confirm-yes="document.getElementById('delete-form-shipment-{{ $transportShipment->id }}').submit();"><i class="ti ti-trash text-white"></i></a>{!! Form::close() !!}</div>@endcan</td></tr>@endforeach</tbody></table></div></div></div></div></div>
@endsection
