@extends('layouts.admin')
@section('page-title', __('Event Tickets'))
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a></li><li class="breadcrumb-item">{{ __('Event Tickets') }}</li>
@endsection
@section('action-btn')
    <div class="float-end d-flex">@can('create event ticket')<a href="#" data-url="{{ route('event-tickets.create') }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Create Event Ticket') }}" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a>@endcan</div>
@endsection
@section('content')
<div class="row"><div class="col-12"><div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable"><thead><tr><th>{{ __('Ticket') }}</th><th>{{ __('Event') }}</th><th>{{ __('Attendee') }}</th><th>{{ __('Status') }}</th><th width="220px">{{ __('Action') }}</th></tr></thead><tbody>@foreach($eventTickets as $eventTicket)<tr><td><div>{{ $eventTicket->ticket_code }}</div><small class="text-muted">{{ Auth::user()->priceFormat($eventTicket->price) }}</small></td><td>{{ optional($eventTicket->event)->title ?: '-' }}</td><td>{{ $eventTicket->attendee_name }}<br><small class="text-muted">{{ $eventTicket->attendee_email ?: '-' }}</small></td><td>{{ __(ucfirst(str_replace('_',' ',$eventTicket->status))) }}</td><td class="Action"><div class="action-btn me-2"><a href="{{ route('event-tickets.show',$eventTicket) }}" class="mx-3 btn btn-sm align-items-center bg-warning"><i class="ti ti-eye text-white"></i></a></div>@can('edit event ticket')<div class="action-btn me-2"><a href="#" data-url="{{ route('event-tickets.edit',$eventTicket) }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Edit Event Ticket') }}" class="mx-3 btn btn-sm align-items-center bg-info"><i class="ti ti-pencil text-white"></i></a></div>@endcan @can('delete event ticket')<div class="action-btn">{!! Form::open(['method'=>'DELETE','route'=>['event-tickets.destroy',$eventTicket],'id'=>'delete-form-ticket-'.$eventTicket->id]) !!}<a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger" data-confirm="{{ __('Are You Sure?') . '|' . __('This action can not be undone. Do you want to continue?') }}" data-confirm-yes="document.getElementById('delete-form-ticket-{{ $eventTicket->id }}').submit();"><i class="ti ti-trash text-white"></i></a>{!! Form::close() !!}</div>@endcan</td></tr>@endforeach</tbody></table></div></div></div></div></div>
@endsection
