<div class="row">
    <div class="col-md-6 mb-3"><label class="form-label">{{ __('Title') }}</label><input type="text" name="title" class="form-control" value="{{ old('title', $okrObjective->title ?? '') }}" required></div>
    <div class="col-md-3 mb-3"><label class="form-label">{{ __('Owner') }}</label><select name="owner_id" class="form-control"><option value="">{{ __('Select owner') }}</option>@foreach($owners as $ownerId => $ownerName)<option value="{{ $ownerId }}" @selected(old('owner_id', $okrObjective->owner_id ?? '') == $ownerId)>{{ $ownerName }}</option>@endforeach</select></div>
    <div class="col-md-3 mb-3"><label class="form-label">{{ __('Linked project') }}</label><select name="project_id" class="form-control"><option value="">{{ __('Optional') }}</option>@foreach($projects as $projectId => $projectName)<option value="{{ $projectId }}" @selected(old('project_id', $okrObjective->project_id ?? '') == $projectId)>{{ $projectName }}</option>@endforeach</select></div>
    <div class="col-md-3 mb-3"><label class="form-label">{{ __('Cycle') }}</label><input type="text" name="cycle" class="form-control" value="{{ old('cycle', $okrObjective->cycle ?? '') }}" placeholder="{{ __('Q2 2026') }}"></div>
    <div class="col-md-3 mb-3"><label class="form-label">{{ __('Status') }}</label><select name="status" class="form-control">@foreach($statuses as $statusKey => $statusLabel)<option value="{{ $statusKey }}" @selected(old('status', $okrObjective->status ?? 'draft') == $statusKey)>{{ __($statusLabel) }}</option>@endforeach</select></div>
    <div class="col-md-3 mb-3"><label class="form-label">{{ __('Progress %') }}</label><input type="number" step="0.01" min="0" max="100" name="progress" class="form-control" value="{{ old('progress', $okrObjective->progress ?? 0) }}"></div>
    <div class="col-md-3 mb-3"><label class="form-label">{{ __('Start date') }}</label><input type="date" name="start_date" class="form-control" value="{{ old('start_date', $okrObjective->start_date ?? '') }}"></div>
    <div class="col-md-3 mb-3"><label class="form-label">{{ __('End date') }}</label><input type="date" name="end_date" class="form-control" value="{{ old('end_date', $okrObjective->end_date ?? '') }}"></div>
    <div class="col-md-12 mb-3"><label class="form-label">{{ __('Description') }}</label><textarea name="description" class="form-control" rows="4">{{ old('description', $okrObjective->description ?? '') }}</textarea></div>
</div>
