<?php

return [
    'modules' => [
        'crm' => [
            'name' => 'CRM',
            'category' => 'revenue',
            'priority' => 'high',
            'advanced_features' => [
                'Lead scoring dynamique',
                'Playbooks commerciaux par pipeline',
                'Détection d\'inactivité et relance automatique',
                'Vue 360 client avec santé de compte',
            ],
            'kpis' => ['pipeline_velocity', 'conversion_rate', 'win_rate'],
        ],
        'sales' => [
            'name' => 'Sales',
            'category' => 'revenue',
            'priority' => 'high',
            'advanced_features' => [
                'CPQ avancé avec remises contrôlées',
                'Prévision pondérée par probabilité',
                'Validation devis au-delà de seuil',
                'Catalogue d\'offres packagées',
            ],
            'kpis' => ['average_deal_size', 'quote_cycle_time', 'forecast_accuracy'],
        ],
        'accounting' => [
            'name' => 'Accounting',
            'category' => 'finance',
            'priority' => 'high',
            'advanced_features' => [
                'Relances clients automatisées',
                'Analyse d\'aging et risque de recouvrement',
                'Clôture périodique avec contrôles',
                'Réconciliation bancaire assistée',
            ],
            'kpis' => ['dso', 'overdue_amount', 'cash_collection_rate'],
        ],
        'billing' => [
            'name' => 'Billing',
            'category' => 'finance',
            'priority' => 'high',
            'advanced_features' => [
                'Facturation récurrente',
                'Prorata upgrades et downgrades',
                'Gestion des échecs de paiement',
                'Blocage client sur limite de crédit',
            ],
            'kpis' => ['billing_recovery_rate', 'failed_payment_rate', 'invoice_accuracy'],
        ],
        'saas' => [
            'name' => 'SaaS',
            'category' => 'platform',
            'priority' => 'high',
            'advanced_features' => [
                'MRR / ARR / churn',
                'Essais limités avec conversion assistée',
                'Feature flags par plan',
                'Surconsommation et upsell automatique',
            ],
            'kpis' => ['mrr', 'arr', 'logo_churn', 'expansion_revenue'],
        ],
        'inventory' => [
            'name' => 'Inventory',
            'category' => 'operations',
            'priority' => 'high',
            'advanced_features' => [
                'Lots et séries',
                'Réapprovisionnement min/max',
                'Alertes de péremption',
                'Réservation intelligente de stock',
            ],
            'kpis' => ['stock_turnover', 'stockout_rate', 'expiry_loss'],
        ],
        'wms' => [
            'name' => 'WMS',
            'category' => 'operations',
            'priority' => 'high',
            'advanced_features' => [
                'Optimisation d\'emplacements',
                'Inventaire mobile',
                'Picking par vague',
                'Cross-docking et transferts assistés',
            ],
            'kpis' => ['pick_accuracy', 'putaway_time', 'warehouse_utilization'],
        ],
        'mrp' => [
            'name' => 'MRP',
            'category' => 'operations',
            'priority' => 'high',
            'advanced_features' => [
                'Calcul des besoins nets',
                'Simulation de pénuries',
                'Ordres suggérés',
                'Planification matière multi-entrepôts',
            ],
            'kpis' => ['material_availability', 'shortage_risk', 'planned_vs_actual'],
        ],
        'production' => [
            'name' => 'Production',
            'category' => 'operations',
            'priority' => 'high',
            'advanced_features' => [
                'Capacité finie',
                'TRS / OEE',
                'Ordres multi-opérations',
                'Analyse temps standard vs réel',
            ],
            'kpis' => ['oee', 'throughput', 'schedule_adherence'],
        ],
        'quality' => [
            'name' => 'Quality',
            'category' => 'operations',
            'priority' => 'high',
            'advanced_features' => [
                'Plans de contrôle',
                'Non-conformités et CAPA',
                'Échantillonnage intelligent',
                'Blocage lot non conforme',
            ],
            'kpis' => ['first_pass_yield', 'nc_rate', 'capa_closure_time'],
        ],
        'maintenance' => [
            'name' => 'Maintenance',
            'category' => 'operations',
            'priority' => 'high',
            'advanced_features' => [
                'Préventif par compteur',
                'Prédictif par usage',
                'Calendrier interventions',
                'Coût complet par équipement',
            ],
            'kpis' => ['mtbf', 'mttr', 'maintenance_cost_ratio'],
        ],
        'projects' => [
            'name' => 'Projects',
            'category' => 'delivery',
            'priority' => 'medium',
            'advanced_features' => [
                'Coût réel vs budget',
                'Détection dérive planning',
                'Allocation par compétence',
                'Risques et dépendances critiques',
            ],
            'kpis' => ['budget_variance', 'schedule_variance', 'resource_utilization'],
        ],
        'hrm' => [
            'name' => 'HRM',
            'category' => 'people',
            'priority' => 'medium',
            'advanced_features' => [
                'Objectifs et revues',
                'Matrice de compétences',
                'Plans de succession',
                'Alertes paie / congés',
            ],
            'kpis' => ['attrition', 'leave_balance_risk', 'performance_completion'],
        ],
        'hrops' => [
            'name' => 'HR Ops',
            'category' => 'people',
            'priority' => 'medium',
            'advanced_features' => [
                'Onboarding / offboarding automatisé',
                'Conformité documentaire',
                'Suivi médical et habilitations',
                'Cas RH avec SLA',
            ],
            'kpis' => ['onboarding_cycle_time', 'document_compliance', 'case_sla'],
        ],
        'hotel' => [
            'name' => 'Hotel',
            'category' => 'industry',
            'priority' => 'high',
            'advanced_features' => [
                'Pricing dynamique',
                'Yield management',
                'Housekeeping par SLA',
                'Upsell avant arrivée',
            ],
            'kpis' => ['occupancy_rate', 'revpar', 'upsell_conversion'],
        ],
        'traceability' => [
            'name' => 'Traceability',
            'category' => 'industry',
            'priority' => 'high',
            'advanced_features' => [
                'Passeport produit',
                'Chaîne de traçabilité amont/aval',
                'Rappels lots',
                'Conformité et certificats',
            ],
            'kpis' => ['trace_coverage', 'recall_readiness', 'certificate_validity'],
        ],
        'cropplanning' => [
            'name' => 'Crop Planning',
            'category' => 'industry',
            'priority' => 'high',
            'advanced_features' => [
                'Rotation culturale',
                'Alertes météo et risques',
                'Intrants recommandés',
                'Optimisation rendement / marge',
            ],
            'kpis' => ['yield_forecast', 'weather_risk', 'parcel_margin'],
        ],
        'cooperative' => [
            'name' => 'Cooperative',
            'category' => 'industry',
            'priority' => 'high',
            'advanced_features' => [
                'Répartition revenus',
                'Suivi apports membres',
                'Paiements et retenues',
                'Transparence coopérative',
            ],
            'kpis' => ['member_payout_accuracy', 'delivery_compliance', 'distribution_cycle'],
        ],
        'hedging' => [
            'name' => 'Hedging',
            'category' => 'industry',
            'priority' => 'high',
            'advanced_features' => [
                'Exposition matière première',
                'Couverture contractuelle',
                'Indices de prix et alertes',
                'Suivi PnL couverture',
            ],
            'kpis' => ['hedge_coverage_ratio', 'price_exposure', 'hedge_pnl'],
        ],
        'btp' => [
            'name' => 'BTP',
            'category' => 'industry',
            'priority' => 'high',
            'advanced_features' => [
                'Suivi avancement chantier',
                'Budget chantier',
                'Sous-traitance et retenues',
                'Maintenance engins',
            ],
            'kpis' => ['site_progress', 'cost_variance', 'equipment_uptime'],
        ],
        'integrations' => [
            'name' => 'Integrations',
            'category' => 'platform',
            'priority' => 'high',
            'advanced_features' => [
                'Webhooks avec retry',
                'Connecteurs low-code',
                'Mapping de données',
                'Monitoring des flux',
            ],
            'kpis' => ['delivery_success_rate', 'retry_rate', 'integration_latency'],
        ],
        'platform' => [
            'name' => 'Platform',
            'category' => 'platform',
            'priority' => 'high',
            'advanced_features' => [
                'Catalogue de fonctionnalités',
                'Workflows transverses',
                'Dashboards analytiques',
                'Audit et gouvernance',
            ],
            'kpis' => ['workflow_success_rate', 'audit_coverage', 'dashboard_adoption'],
        ],
        'chatgpt' => [
            'name' => 'ChatGPT',
            'category' => 'platform',
            'priority' => 'medium',
            'advanced_features' => [
                'Copilote métier par module',
                'Synthèse d\'activité',
                'Génération de documents',
                'Assistance à la décision',
            ],
            'kpis' => ['assistant_usage', 'time_saved', 'template_reuse'],
        ],
        'approvals' => [
            'name' => 'Approvals',
            'category' => 'platform',
            'priority' => 'high',
            'advanced_features' => [
                'Matrice multi-niveaux',
                'Escalades SLA',
                'Approbation parallèle',
                'Délégation temporaire',
            ],
            'kpis' => ['approval_cycle_time', 'sla_breach_rate', 'auto_approval_rate'],
        ],
    ],

    'workflow' => [
        'triggers' => [
            'invoice.created' => ['name' => 'Invoice created', 'module' => 'billing', 'model' => App\Models\Invoice::class],
            'invoice.paid' => ['name' => 'Invoice paid', 'module' => 'billing', 'model' => App\Models\Invoice::class],
            'invoice.overdue' => ['name' => 'Invoice overdue', 'module' => 'billing', 'model' => App\Models\Invoice::class],
            App\Models\Invoice::class => ['name' => 'Invoice record', 'module' => 'billing'],
            App\Models\Lead::class => ['name' => 'Lead record', 'module' => 'crm'],
            'lead.stage_changed' => ['name' => 'Lead stage changed', 'module' => 'crm', 'model' => App\Models\Lead::class],
            App\Models\Customer::class => ['name' => 'Customer record', 'module' => 'crm'],
            App\Models\Project::class => ['name' => 'Project record', 'module' => 'projects'],
            'project.completed' => ['name' => 'Project completed', 'module' => 'projects', 'model' => App\Models\Project::class],
            App\Models\Employee::class => ['name' => 'Employee record', 'module' => 'hrm'],
            App\Models\ProductionOrder::class => ['name' => 'Production order', 'module' => 'production'],
            App\Models\ProductionQualityCheck::class => ['name' => 'Quality check', 'module' => 'quality'],
            App\Models\ApprovalRequest::class => ['name' => 'Approval request', 'module' => 'approvals'],
            App\Models\HotelReservation::class => ['name' => 'Hotel reservation', 'module' => 'hotel'],
            App\Models\AgriHarvestDelivery::class => ['name' => 'Harvest delivery', 'module' => 'cooperative'],
            App\Models\Order::class => ['name' => 'SaaS order', 'module' => 'saas'],
        ],
        'actions' => [
            'email' => ['name' => 'Send email', 'description' => 'Send a plain text email to a resolved address.'],
            'notification' => ['name' => 'Create notification', 'description' => 'Create an in-app notification when the table exists.'],
            'task' => ['name' => 'Create task', 'description' => 'Create a follow-up task when the task table exists.'],
            'update_field' => ['name' => 'Update field', 'description' => 'Update a model attribute from the workflow.'],
            'webhook' => ['name' => 'Dispatch webhook', 'description' => 'Send payload to a webhook URL or configured integration.'],
            'audit_log' => ['name' => 'Write audit log', 'description' => 'Persist a structured audit entry.'],
            'approval_request' => ['name' => 'Create approval request', 'description' => 'Open a pending approval request for the resource.'],
            'zapier_hook' => ['name' => 'Dispatch Zapier hook', 'description' => 'Trigger matching Zapier hooks for the event.'],
        ],
        'templates' => [
            [
                'key' => 'invoice-overdue-escalation',
                'name' => 'Invoice overdue escalation',
                'trigger' => 'invoice.overdue',
                'conditions' => [
                    ['field' => 'status', 'operator' => 'not_equals', 'value' => 'Paid'],
                ],
                'actions' => [
                    ['type' => 'audit_log', 'data' => ['action' => 'invoice.overdue']],
                    ['type' => 'approval_request', 'data' => ['resource_type' => App\Models\Invoice::class]],
                ],
            ],
            [
                'key' => 'lead-hot-followup',
                'name' => 'Hot lead follow-up',
                'trigger' => App\Models\Lead::class,
                'conditions' => [
                    ['field' => 'subject', 'operator' => 'is_not_empty'],
                ],
                'actions' => [
                    ['type' => 'audit_log', 'data' => ['action' => 'lead.hot_followup']],
                    ['type' => 'webhook', 'data' => ['body' => 'Lead requires fast follow-up']],
                ],
            ],
            [
                'key' => 'production-quality-gate',
                'name' => 'Production quality gate',
                'trigger' => App\Models\ProductionQualityCheck::class,
                'conditions' => [
                    ['field' => 'status', 'operator' => 'equals', 'value' => 'failed'],
                ],
                'actions' => [
                    ['type' => 'approval_request', 'data' => ['resource_type' => App\Models\ProductionQualityCheck::class]],
                    ['type' => 'audit_log', 'data' => ['action' => 'quality.failed']],
                ],
            ],
        ],
    ],

    'roadmap' => [
        'wave_1' => ['Approvals', 'Platform', 'Integrations', 'Accounting', 'Billing'],
        'wave_2' => ['CRM', 'Sales', 'Projects', 'HRM', 'HrOps'],
        'wave_3' => ['Inventory', 'WMS', 'MRP', 'Production', 'Quality', 'Maintenance'],
        'wave_4' => ['Hotel', 'Traceability', 'Crop Planning', 'Cooperative', 'Hedging', 'BTP'],
    ],

    'expansion_candidates' => [
        'client_supplier_portal' => ['priority' => 'P1', 'value' => 'very_high', 'depends_on' => ['crm', 'sales', 'billing', 'support']],
        'dms' => ['priority' => 'P1', 'value' => 'very_high', 'depends_on' => ['platform', 'hrops', 'quality']],
        'esign' => ['priority' => 'P1', 'value' => 'high', 'depends_on' => ['dms', 'sales', 'hrm']],
        'workflow_designer' => ['priority' => 'P1', 'value' => 'very_high', 'depends_on' => ['approvals', 'platform']],
        'expense_management' => ['priority' => 'P1', 'value' => 'high', 'depends_on' => ['hrm', 'accounting', 'approvals']],
        'advanced_procurement' => ['priority' => 'P1', 'value' => 'very_high', 'depends_on' => ['accounting', 'inventory', 'approvals']],
        'employee_portal' => ['priority' => 'P1', 'value' => 'high', 'depends_on' => ['hrm', 'hrops']],
        'advanced_bi' => ['priority' => 'P1', 'value' => 'very_high', 'depends_on' => ['platform', 'accounting', 'sales', 'projects']],
        'contracts_recurring_revenue' => ['priority' => 'P1', 'value' => 'high', 'depends_on' => ['billing', 'sales', 'saas']],
        'whatsapp_omnichannel' => ['priority' => 'P1', 'value' => 'high', 'depends_on' => ['crm', 'integrations', 'platform']],
        'field_service' => ['priority' => 'P2', 'value' => 'high', 'depends_on' => ['maintenance', 'projects', 'inventory']],
        'asset_management' => ['priority' => 'P2', 'value' => 'high', 'depends_on' => ['accounting', 'maintenance']],
        'knowledge_base' => ['priority' => 'P2', 'value' => 'medium', 'depends_on' => ['platform', 'support']],
        'booking_engine' => ['priority' => 'P2', 'value' => 'high', 'depends_on' => ['integrations', 'platform']],
        'lms' => ['priority' => 'P2', 'value' => 'high', 'depends_on' => ['hrm', 'hrops']],
        'grc' => ['priority' => 'P2', 'value' => 'high', 'depends_on' => ['quality', 'platform', 'approvals']],
        'ecommerce_connectors' => ['priority' => 'P2', 'value' => 'very_high', 'depends_on' => ['sales', 'inventory', 'integrations']],
        'shipping_delivery' => ['priority' => 'P2', 'value' => 'high', 'depends_on' => ['wms', 'inventory', 'sales']],
        'fleet' => ['priority' => 'P3', 'value' => 'medium', 'depends_on' => ['maintenance', 'operations']],
        'advanced_cmms' => ['priority' => 'P3', 'value' => 'high', 'depends_on' => ['maintenance', 'inventory']],
        'iot' => ['priority' => 'P3', 'value' => 'very_high', 'depends_on' => ['integrations', 'maintenance', 'quality']],
        'esg' => ['priority' => 'P3', 'value' => 'medium', 'depends_on' => ['platform', 'advanced_bi']],
        'franchise_multisite' => ['priority' => 'P3', 'value' => 'high', 'depends_on' => ['saas', 'pos', 'inventory']],
        'loyalty' => ['priority' => 'P3', 'value' => 'high', 'depends_on' => ['crm', 'pos', 'sales']],
        'legal' => ['priority' => 'P3', 'value' => 'medium', 'depends_on' => ['dms', 'esign', 'contracts_recurring_revenue']],
    ],
];
