@extends('layouts.admin')
@section('page-title', __('Leasing Contracts'))
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a></li><li class="breadcrumb-item">{{ __('Leasing Contracts') }}</li>
@endsection
@section('action-btn')
    <div class="float-end d-flex">@can('create leasing contract')<a href="#" data-url="{{ route('leasing-contracts.create') }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Create Leasing Contract') }}" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a>@endcan</div>
@endsection
@section('content')
<div class="row"><div class="col-12"><div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable"><thead><tr><th>{{ __('Contract') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Asset') }}</th><th>{{ __('Status') }}</th><th width="220px">{{ __('Action') }}</th></tr></thead><tbody>@foreach($leasingContracts as $leasingContract)<tr><td><div>{{ $leasingContract->contract_number }}</div><small class="text-muted">{{ Auth::user()->priceFormat($leasingContract->lease_amount) }}</small></td><td>{{ optional($leasingContract->customer)->name ?: '-' }}</td><td>{{ $leasingContract->asset_name }}</td><td>{{ __(ucfirst($leasingContract->status)) }}</td><td class="Action"><div class="action-btn me-2"><a href="{{ route('leasing-contracts.show',$leasingContract) }}" class="mx-3 btn btn-sm align-items-center bg-warning"><i class="ti ti-eye text-white"></i></a></div>@can('edit leasing contract')<div class="action-btn me-2"><a href="#" data-url="{{ route('leasing-contracts.edit',$leasingContract) }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Edit Leasing Contract') }}" class="mx-3 btn btn-sm align-items-center bg-info"><i class="ti ti-pencil text-white"></i></a></div>@endcan @can('delete leasing contract')<div class="action-btn">{!! Form::open(['method'=>'DELETE','route'=>['leasing-contracts.destroy',$leasingContract],'id'=>'delete-form-leasing-'.$leasingContract->id]) !!}<a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger" data-confirm="{{ __('Are You Sure?') . '|' . __('This action can not be undone. Do you want to continue?') }}" data-confirm-yes="document.getElementById('delete-form-leasing-{{ $leasingContract->id }}').submit();"><i class="ti ti-trash text-white"></i></a>{!! Form::close() !!}</div>@endcan</td></tr>@endforeach</tbody></table></div></div></div></div></div>
@endsection
