@extends('layouts.admin')
@section('page-title', __('Microfinance Loans'))
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a></li><li class="breadcrumb-item">{{ __('Microfinance Loans') }}</li>
@endsection
@section('action-btn')
    <div class="float-end d-flex">@can('create microfinance loan')<a href="#" data-url="{{ route('microfinance-loans.create') }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Create Microfinance Loan') }}" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a>@endcan</div>
@endsection
@section('content')
<div class="row"><div class="col-12"><div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable"><thead><tr><th>{{ __('Loan') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Amount') }}</th><th>{{ __('Status') }}</th><th width="220px">{{ __('Action') }}</th></tr></thead><tbody>@foreach($microfinanceLoans as $microfinanceLoan)<tr><td><div>{{ $microfinanceLoan->loan_number }}</div><small class="text-muted">{{ $microfinanceLoan->purpose ?: '-' }}</small></td><td>{{ optional($microfinanceLoan->customer)->name ?: '-' }}</td><td>{{ Auth::user()->priceFormat($microfinanceLoan->principal_amount) }}</td><td>{{ __(ucfirst($microfinanceLoan->status)) }}</td><td class="Action"><div class="action-btn me-2"><a href="{{ route('microfinance-loans.show',$microfinanceLoan) }}" class="mx-3 btn btn-sm align-items-center bg-warning"><i class="ti ti-eye text-white"></i></a></div>@can('edit microfinance loan')<div class="action-btn me-2"><a href="#" data-url="{{ route('microfinance-loans.edit',$microfinanceLoan) }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Edit Microfinance Loan') }}" class="mx-3 btn btn-sm align-items-center bg-info"><i class="ti ti-pencil text-white"></i></a></div>@endcan @can('delete microfinance loan')<div class="action-btn">{!! Form::open(['method'=>'DELETE','route'=>['microfinance-loans.destroy',$microfinanceLoan],'id'=>'delete-form-microfinance-'.$microfinanceLoan->id]) !!}<a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger" data-confirm="{{ __('Are You Sure?') . '|' . __('This action can not be undone. Do you want to continue?') }}" data-confirm-yes="document.getElementById('delete-form-microfinance-{{ $microfinanceLoan->id }}').submit();"><i class="ti ti-trash text-white"></i></a>{!! Form::close() !!}</div>@endcan</td></tr>@endforeach</tbody></table></div></div></div></div></div>
@endsection
