@extends('layouts.admin')
@section('page-title', $savedReport->name)
@section('page-subtitle', __('Run saved reports on demand and schedule digest delivery for decision makers.'))
@section('content')
<div class="row">
<div class="col-md-8">
    <div class="row mb-3">
        <div class="col-md-4"><div class="card"><div class="card-body"><span class="text-muted d-block small">{{ __('Rows') }}</span><h3 class="mb-0">{{ $result['count'] }}</h3></div></div></div>
        <div class="col-md-4"><div class="card"><div class="card-body"><span class="text-muted d-block small">{{ __('Columns') }}</span><h3 class="mb-0">{{ count($result['columns']) }}</h3></div></div></div>
        <div class="col-md-4"><div class="card"><div class="card-body"><span class="text-muted d-block small">{{ __('Last Run') }}</span><h6 class="mb-0">{{ optional($savedReport->last_run_at)->diffForHumans() ?: __('Just now') }}</h6></div></div></div>
    </div>
    <div class="card"><div class="card-header"><h5>{{ __('Report Result') }}</h5></div><div class="card-body table-border-style"><table class="table"><thead><tr>@foreach($result['columns'] as $column)<th>{{ $column }}</th>@endforeach</tr></thead><tbody>@forelse($result['rows'] as $row)<tr>@foreach($result['columns'] as $column)<td>{{ data_get($row, $column) }}</td>@endforeach</tr>@empty<tr><td colspan="{{ max(count($result['columns']),1) }}" class="text-muted">{{ __('No rows found.') }}</td></tr>@endforelse</tbody></table></div></div>
</div>
<div class="col-md-4"><div class="card mb-3"><div class="card-header"><h5>{{ __('Schedule by Email') }}</h5></div><div class="card-body"><form method="POST" action="{{ route('core.reports.schedule', $savedReport) }}">@csrf <div class="mb-2"><label class="form-label">{{ __('Name') }}</label><input type="text" name="name" class="form-control" required></div><div class="mb-2"><label class="form-label">{{ __('Frequency') }}</label><select name="frequency" class="form-control"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></div><div class="mb-2"><label class="form-label">{{ __('Recipients') }}</label><input type="text" name="recipients" class="form-control" placeholder="a@b.com,c@d.com" required></div><button class="btn btn-primary">{{ __('Save Schedule') }}</button></form></div></div><div class="card"><div class="card-header"><h5>{{ __('Existing Schedules') }}</h5></div><div class="card-body">@forelse($schedules as $schedule)<div class="border rounded p-2 mb-2 d-flex justify-content-between align-items-center"><div><div class="fw-semibold">{{ $schedule->name }}</div><small class="text-muted">{{ ucfirst($schedule->frequency) }} • {{ implode(', ', $schedule->recipients ?? []) }}</small></div><form method="POST" action="{{ route('core.reports.schedule.toggle', $schedule) }}">@csrf <button class="btn btn-sm {{ $schedule->is_active ? 'btn-warning' : 'btn-success' }}">{{ $schedule->is_active ? __('Pause') : __('Resume') }}</button></form></div>@empty<div class="text-muted">{{ __('No schedules configured.') }}</div>@endforelse</div></div></div>
<div class="col-md-4"><div class="card mb-3"><div class="card-header"><h5>{{ __('Schedule by Email') }}</h5></div><div class="card-body"><form method="POST" action="{{ route('core.reports.schedule', $savedReport) }}">@csrf <div class="mb-2"><label class="form-label">{{ __('Name') }}</label><input type="text" name="name" class="form-control" required></div><div class="mb-2"><label class="form-label">{{ __('Frequency') }}</label><select name="frequency" class="form-control"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></div><div class="mb-2"><label class="form-label">{{ __('Recipients') }}</label><input type="text" name="recipients" class="form-control" placeholder="a@b.com,c@d.com" required></div><button class="btn btn-primary">{{ __('Save Schedule') }}</button></form></div></div><div class="card"><div class="card-header"><h5>{{ __('Existing Schedules') }}</h5></div><div class="card-body">@forelse($schedules as $schedule)<div class="border rounded p-2 mb-2"><div class="d-flex justify-content-between align-items-start gap-2"><div><div class="fw-semibold">{{ $schedule->name }}</div><small class="text-muted">{{ ucfirst($schedule->frequency) }} • {{ implode(', ', $schedule->recipients ?? []) }}</small><div class="small text-muted mt-1">{{ __('Last sent') }}: {{ optional($schedule->last_sent_at)->diffForHumans() ?: __('Never') }}</div></div><div class="d-flex gap-2"><form method="POST" action="{{ route('core.reports.schedule.send', $schedule) }}">@csrf <button class="btn btn-sm btn-light">{{ __('Send now') }}</button></form><form method="POST" action="{{ route('core.reports.schedule.toggle', $schedule) }}">@csrf <button class="btn btn-sm {{ $schedule->is_active ? 'btn-warning' : 'btn-success' }}">{{ $schedule->is_active ? __('Pause') : __('Resume') }}</button></form></div></div></div>@empty<div class="text-muted">{{ __('No schedules configured.') }}</div>@endforelse</div></div></div>
</div>
@endsection
