@extends('layouts.admin')
@section('page-title', __('Product Lifecycle'))
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a></li><li class="breadcrumb-item">{{ __('Product Lifecycle') }}</li>
@endsection
@section('action-btn')
    <div class="float-end d-flex">@can('create product lifecycle record')<a href="#" data-url="{{ route('product-lifecycle-records.create') }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Create Lifecycle Record') }}" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a>@endcan</div>
@endsection
@section('content')
<div class="row"><div class="col-12"><div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Stage') }}</th><th>{{ __('Owner') }}</th><th>{{ __('Status') }}</th><th>{{ __('Date') }}</th><th width="220px">{{ __('Action') }}</th></tr></thead><tbody>@foreach($productLifecycleRecords as $productLifecycleRecord)<tr><td>{{ optional($productLifecycleRecord->productService)->name ?: '-' }}</td><td>{{ __(ucfirst($productLifecycleRecord->stage)) }}</td><td>{{ optional($productLifecycleRecord->owner)->name ?: '-' }}</td><td>{{ __(ucfirst($productLifecycleRecord->status)) }}</td><td>{{ $productLifecycleRecord->effective_date ? Auth::user()->dateFormat($productLifecycleRecord->effective_date) : '-' }}</td><td class="Action"><div class="action-btn me-2"><a href="{{ route('product-lifecycle-records.show',$productLifecycleRecord) }}" class="mx-3 btn btn-sm align-items-center bg-warning"><i class="ti ti-eye text-white"></i></a></div>@can('edit product lifecycle record')<div class="action-btn me-2"><a href="#" data-url="{{ route('product-lifecycle-records.edit',$productLifecycleRecord) }}" data-size="lg" data-ajax-popup="true" data-title="{{ __('Edit Lifecycle Record') }}" class="mx-3 btn btn-sm align-items-center bg-info"><i class="ti ti-pencil text-white"></i></a></div>@endcan @can('delete product lifecycle record')<div class="action-btn">{!! Form::open(['method'=>'DELETE','route'=>['product-lifecycle-records.destroy',$productLifecycleRecord],'id'=>'delete-form-plm-'.$productLifecycleRecord->id]) !!}<a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger" data-confirm="{{ __('Are You Sure?') . '|' . __('This action can not be undone. Do you want to continue?') }}" data-confirm-yes="document.getElementById('delete-form-plm-{{ $productLifecycleRecord->id }}').submit();"><i class="ti ti-trash text-white"></i></a>{!! Form::close() !!}</div>@endcan</td></tr>@endforeach</tbody></table></div></div></div></div></div>
@endsection
